'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const catalog=require('../data/alexandria_catalog.json');
const provider='treasury-fiscal-data',cap='debt/to-the-penny';
function fresh(){delete require.cache[require.resolve('../alexandria-src/router')];return {router:require('../alexandria-src/router')};}
function json(body,status=200,headers={}){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json',...headers}});}
async function mocked(fn,body){const old=global.fetch;global.fetch=fn;try{return await body();}finally{global.fetch=old;}}
function envelope(cost=0){return {success:true,data:{alexandria:[{provider,capability:cap,creditsCost:cost,data:[{record_date:'2026-01-01'}]}]}};}
async function paid(raw){const old=process.env.FIRECRAWL_API_KEY;process.env.FIRECRAWL_API_KEY='offline-test-not-secret';try{return await mocked(async()=>json(raw),()=>fresh().router.query(provider,cap,{}, {gateway:true,confirm:true}));}finally{if(old===undefined)delete process.env.FIRECRAWL_API_KEY;else process.env.FIRECRAWL_API_KEY=old;}}
test('provider exact raw response and zero credits retained',async()=>{const raw=envelope(0);const r=await paid(raw);assert.equal(r.status,'ok');assert.equal(r.creditsUsed,0);assert.deepEqual(r.response,raw);});
test('provider missing or invalid credit remains unknown',async()=>{for(const value of [undefined,null,-1,'5']){const raw=envelope();if(value===undefined)delete raw.data.alexandria[0].creditsCost;else raw.data.alexandria[0].creditsCost=value;assert.equal((await paid(raw)).creditsUsed,null);}});
test('provider empty error wrong capability and multiple results classified',async()=>{const empty=envelope();empty.data.alexandria[0].data=[];assert.equal((await paid(empty)).status,'empty');for(const change of [r=>r.success=false,r=>r.data.alexandria[0].error='bad',r=>r.data.alexandria[0].capability='wrong',r=>r.data.alexandria.push({...r.data.alexandria[0]})]){const raw=envelope();change(raw);const r=await paid(raw);assert.equal(r.status,'error');assert.deepEqual(r.response,raw);}});
test('provider transport failure submitted once with uncertain completion',async()=>{let calls=0;const old=process.env.FIRECRAWL_API_KEY;process.env.FIRECRAWL_API_KEY='offline-test-not-secret';try{await mocked(async()=>{calls++;throw Error('socket closed');},async()=>{const r=await fresh().router.query(provider,cap,{}, {gateway:true,confirm:true});assert.equal(r.status,'error');assert.equal(r.requestMayHaveCompleted,true);assert.equal(r.creditsUsed,null);});}finally{if(old===undefined)delete process.env.FIRECRAWL_API_KEY;else process.env.FIRECRAWL_API_KEY=old;}assert.equal(calls,1);});
test('provider JSON null preserves original response on error',async()=>{const r=await paid(null);assert.equal(r.status,'error');assert.ok(Object.hasOwn(r,'response'));assert.equal(r.response,null);});
test('captures made in same millisecond preserve both raw observations',()=>{const os=require('node:os'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'lfc-review-'));const RealDate=Date;global.Date=class extends RealDate{constructor(...a){super(...(a.length?a:['2026-10-01T12:00:00.000Z']));}};try{const {encapsulate}=require('../alexandria-src/encapsulation');const base={provider,capability:cap,creditsUsed:null};const first=encapsulate({...base,data:[{value:1}]},tmp);const second=encapsulate({...base,data:[{value:2}]},tmp);assert.notEqual(first.rawFilePath,second.rawFilePath);assert.equal(JSON.parse(fs.readFileSync(first.rawFilePath)).data[0].value,1);}finally{global.Date=RealDate;fs.rmSync(tmp,{recursive:true,force:true});}});
test('all 797 catalog capabilities use official gateway',()=>{const {router}=fresh();let count=0;for(const p of catalog.providers)for(const t of p.tools){const r=router.plan(p.id,t.capability);assert.equal(r.routeDecision,'FIRECRAWL_GATEWAY');assert.equal(r.source,'firecrawl-alexandria-gateway');count++;}assert.equal(count,797);});
test('every unconfirmed operation including Treasury has no network',async()=>mocked(()=>{throw Error('network must not run');},async()=>{const {router}=fresh();for(const p of catalog.providers)for(const t of p.tools){const r=await router.query(p.id,t.capability);assert.equal(r.status,'confirmation_required');assert.equal(r.creditsUsed,null);}}));
test('explicit preview makes no request even with confirm',async()=>mocked(()=>{throw Error('network must not run');},async()=>assert.equal((await fresh().router.query(provider,cap,{}, {preview:true,confirm:true})).status,'preview')));
test('unknown operation and unsafe override reject without request',async()=>mocked(()=>{throw Error('network must not run');},async()=>{const {router}=fresh();await assert.rejects(router.query(provider,'made-up'));await assert.rejects(router.query(provider,cap,{}, {'danger-direct-ip':true}));}));
test('confirmed Treasury requests official Firecrawl only once',async()=>{let calls=0;const old=process.env.FIRECRAWL_API_KEY;process.env.FIRECRAWL_API_KEY='offline-test-not-secret';try{await mocked(async(url,opts)=>{calls++;assert.equal(url,'https://api.firecrawl.dev/v2/scrape');assert.equal(opts.method,'POST');assert.deepEqual(JSON.parse(opts.body).alexandria,{provider,capability:cap,options:{'page[number]':2}});return json(envelope());},async()=>assert.equal((await fresh().router.query(provider,cap,{'page[number]':2},{confirm:true})).status,'ok'));}finally{if(old===undefined)delete process.env.FIRECRAWL_API_KEY;else process.env.FIRECRAWL_API_KEY=old;}assert.equal(calls,1);});
